# Generated by Django 5.0 on 2024-10-13 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('passive', models.BooleanField(
                    default=True, verbose_name='Пассивная')),
                ('damage', models.CharField(choices=[
                 ('full', 'Полный'), ('half', 'Половина')], max_length=255, verbose_name='Урон')),
            ],
            options={
                'verbose_name': 'Способность',
                'verbose_name_plural': 'Способности',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(
                    upload_to='achievements/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration', models.IntegerField(verbose_name='Длительность')),
                ('type', models.CharField(choices=[
                 ('buff', 'Бафф'), ('debuff', 'Дебафф')], max_length=255, verbose_name='Тип')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='base.ability', verbose_name='Способность')),
            ],
            options={
                'verbose_name': 'Эффект',
                'verbose_name_plural': 'Эффекты',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(
                    upload_to='roles/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('abilities', models.ManyToManyField(blank=True,
                 to='base.ability', verbose_name='Способности')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('gender', models.CharField(choices=[
                 ('male', 'М'), ('female', 'Ж')], max_length=255, verbose_name='Пол')),
                ('is_alive', models.BooleanField(
                    default=True, verbose_name='Жив/Мёртв')),
                ('number', models.IntegerField(blank=True,
                 null=True, verbose_name='Номер в игровой сессии')),
                ('health', models.IntegerField(default=100, verbose_name='Здоровье')),
                ('bought', models.BooleanField(default=False)),
                ('effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 to='base.effect', verbose_name='Действующий эффект')),
                ('role', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE, to='base.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание игроков'), ('started', 'Игра началась'), ('finished', 'Игра закончилась'), (
                    'canceled', 'Игра отменена'), ('Day', 'День'), ('Night', 'Ночь')], default='waiting', max_length=255, verbose_name='Статус')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='games_created', to='base.user', verbose_name='Создатель игры')),
                ('players', models.ManyToManyField(
                    blank=True, related_name='games_joined', to='base.user', verbose_name='Игроки')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
