# Generated by Django 5.0 on 2024-10-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='gender',
            field=models.CharField(choices=[('male', 'М'), ('female', 'Ж')], default=123, max_length=255, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
