# Generated by Django 5.0 on 2024-10-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_user_effect_user_effect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='user',
            name='health',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_alive',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Effect',
        ),
    ]
