# Generated by Django 5.0 on 2024-10-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_user_effect_remove_user_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='action_time',
            field=models.IntegerField(default=1, verbose_name='Время действия'),
        ),
    ]
