# Generated by Django 5.0 on 2024-10-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_ability_action_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='action_time',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Время действия'),
        ),
    ]
