# Generated by Django 5.0 on 2024-10-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brithday',
            field=models.DateField(default='2024-01-16', verbose_name='Дата рождения'),
            preserve_default=False,
        ),
    ]
