# Generated by Django 5.0 on 2024-10-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_brithday_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='chat_id',
            field=models.BigIntegerField(default=12, verbose_name='ID чата'),
            preserve_default=False,
        ),
    ]
