# Generated by Django 5.0 on 2024-11-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_game_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_action',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-12 14:53', verbose_name='Последнее действие'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ability',
            name='passive',
            field=models.BooleanField(default=True, verbose_name='Пассивная/Активная'),
        ),
    ]
