# Generated by Django 5.0 on 2024-11-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_user_last_action_alter_ability_passive'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-12 14:55', verbose_name='Время начала игры'),
            preserve_default=False,
        ),
    ]
