# Generated by Django 5.0 on 2024-11-16 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_game_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='player_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.role', verbose_name='Роль игрока'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_action',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время последнего действие'),
        ),
    ]
