# Generated by Django 5.0 on 2024-11-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_user_player_role_alter_user_last_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='creature',
            field=models.CharField(choices=[('human', 'Человек'), ('vampire', 'Вампир'), ('werewolf', 'оборотень')], default='антон', max_length=255, verbose_name='Существо/раса'),
            preserve_default=False,
        ),
    ]
