# Generated by Django 5.0 on 2024-11-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_role_creature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='creature',
            field=models.CharField(choices=[('human', 'Человек'), ('vampire', 'Вампир'), ('werewolf', 'Оборотень')], max_length=255, verbose_name='Существо/раса'),
        ),
    ]
