# Generated by Django 5.0 on 2024-11-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_role_creature'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='boss',
            field=models.BooleanField(default=False, verbose_name='Босс'),
        ),
    ]
