# Generated by Django 5.0 on 2024-11-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_role_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания игры'),
        ),
    ]
