# Generated by Django 5.0 on 2024-11-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_game_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_game_text', models.TextField(blank=True, null=True, verbose_name='Об игре')),
                ('rules_text', models.TextField(blank=True, null=True, verbose_name='Правила')),
                ('start_game_text', models.TextField(blank=True, null=True, verbose_name='Текст при старте игры')),
            ],
            options={
                'verbose_name': 'Сюжетный текст',
                'verbose_name_plural': 'Сюжетные тексты',
            },
        ),
    ]
