# Generated by Django 5.0 on 2024-12-11 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_storytext_day_alter_storytext_night'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProcessJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted', models.BooleanField(default=False, verbose_name='Проголосовал?')),
                ('selected_race', models.CharField(choices=[('human', 'Человек'), ('vampire', 'Вампир'), ('werewolf', 'Оборотень')], default=None, max_length=255, verbose_name='Выбранная раса/существо')),
                ('inited_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.game', verbose_name='Инициированная игра')),
                ('player_in_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_in_game_journal', to='base.user', verbose_name='Игрок')),
                ('selected_victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_victim_journal', to='base.user', verbose_name='выбранная жертва')),
            ],
            options={
                'verbose_name': 'Журнал процесса игры',
                'verbose_name_plural': 'Журналы процесса игр',
            },
        ),
    ]
