# Generated by Django 5.0 on 2024-12-11 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_gameprocessjournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprocessjournal',
            name='selected_race',
            field=models.CharField(blank=True, choices=[('human', 'Человек'), ('vampire', 'Вампир'), ('werewolf', 'Оборотень')], max_length=255, null=True, verbose_name='Выбранная раса/существо'),
        ),
        migrations.AlterField(
            model_name='gameprocessjournal',
            name='selected_victim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_victim_journal', to='base.user', verbose_name='выбранная жертва'),
        ),
    ]
