# Generated by Django 5.0 on 2024-12-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_gameprocessjournal_selected_race_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='damage',
        ),
    ]
