# Generated by Django 5.0 on 2024-12-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_ability_damage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='action_time',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='passive',
        ),
    ]
