# Generated by Django 5.0 on 2024-12-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_ability_action_time_remove_ability_passive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название баффа')),
                ('description', models.TextField(verbose_name='Описание баффа')),
            ],
            options={
                'verbose_name': 'Бафф',
                'verbose_name_plural': 'Баффы',
            },
        ),
        migrations.CreateModel(
            name='Debuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название баффа')),
                ('description', models.TextField(verbose_name='Описание баффа')),
            ],
            options={
                'verbose_name': 'Дебафф',
                'verbose_name_plural': 'Дебаффы',
            },
        ),
        migrations.AddField(
            model_name='gameprocessjournal',
            name='current_buffs',
            field=models.ManyToManyField(blank=True, to='base.buff'),
        ),
        migrations.AddField(
            model_name='gameprocessjournal',
            name='current_debuffs',
            field=models.ManyToManyField(blank=True, to='base.debuff'),
        ),
    ]
