# Generated by Django 5.0 on 2024-12-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_buff_debuff_gameprocessjournal_current_buffs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debuff',
            name='description',
            field=models.TextField(verbose_name='Описание дебаффа'),
        ),
        migrations.AlterField(
            model_name='debuff',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название дебаффа'),
        ),
    ]
