# Generated by Django 5.0 on 2024-12-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_debuff_description_alter_debuff_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoryText',
        ),
    ]
