# Generated by Django 5.0 on 2024-12-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_buff_key_debuff_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='key',
            field=models.CharField(default=1, max_length=255, verbose_name='Ключ'),
            preserve_default=False,
        ),
    ]
